# Generated by Django 5.1.2 on 2024-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_audiofile_session_key_audiofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='temp_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
