# Generated by Django 5.1.2 on 2024-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_audiofile_temp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='temp_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='temp_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
